### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'Splitpanes')

### ISSUE THREAD

**Issue by leo-mangold** [orefalo/svelte-splitpanes#56]
Hey I just installed this package and tried to use it in its simplest form but I get an error:
```
TypeError: Cannot read properties of undefined (reading 'Splitpanes')
     at eval (/src/routes/(root)/+page.svelte:13:66)
     at Object.$$render (/node_modules/svelte/internal/index.mjs:1878:22)
     at Object.default (/.svelte-kit/generated/root.svelte:58:134)
     at eval (/src/routes/+layout.svelte:55:146)
     at Object.$$render (/node_modules/svelte/internal/index.mjs:1878:22)
     at eval (/.svelte-kit/generated/root.svelte:56:126)
     at $$render (/node_modules/svelte/internal/index.mjs:1878:22)
     at Object.render (/node_modules/svelte/internal/index.mjs:1886:26)
     at render_response 
```
My Code:
```
<script>
  import { Pane, Splitpanes } from "svelte-splitpanes";
</script>

<Splitpanes theme="" class="" id="panes">
  <Pane class="p-4">Hello</Pane>
  <Pane class="p-4">World</Pane>
</Splitpanes>
```

**Comment by orefalo** [comment]
Hi,

Your code works perfectly from REPL

https://svelte.dev/repl/657f973a5f7f44ab93a1b04acfebcb83?version=3.55.1

Must be something else,

**Comment by Tal500** [comment]
Please give us a simple reproduction example

**Comment by leo-mangold** [comment]
I'll try to create an example.
The problem occurs on a page reload. So on first load everything works fine but when I refresh I get this client error on the server and the client gets an error. This leads to being sent to the error page and when I go back everything is normal again.
Do you at least have the slightest idea of what could cause this error on reload, because I have no clue what so ever?

**Comment by leo-mangold** [comment]
I am very sorry but apparently my node just had some problems. I restarted the server and now it works, although I already tried that yesterday...
But thanks anyway :)
